package com.lima2017.neuralguide.api;

import android.support.annotation.NonNull;

import java.net.HttpURLConnection;
import java.util.HashSet;
import java.util.Set;

/**
 * A DTO for passing the results of an image captioning attempt to the user.
 *
 * For Neural Guide WebAPI v0.1
 *
 * @author Henry Thompson
 * @version 1.0
 */

public class ImageCaptionResult {
    /** The status code of the captioning attempt. */
    private final int _statusCode;

    /** The actual caption returned by the server. */
    private final String _caption;

    /** The list of improvements suggested by the server. */
    private final Set<ImprovementTip> _improvementTips;

    /**
     * The result of querying the API to obtain a caption for the image.
     * @param statusCode The status code associated with the result.
     * @param caption The actual caption returned.
     */
    public ImageCaptionResult(@NonNull final int statusCode, @NonNull final String caption) {
        _statusCode = statusCode;
        _caption = caption;
        _improvementTips = new HashSet<>();
    }

    /**
     * @return <code>true</code> if and only if the API successfully generated a caption for the
     * image, even if it is not confident about the result.
     */
    public boolean success() {
        return _statusCode == HttpURLConnection.HTTP_OK;
    }

    /**
     * @return The HTTP status code returned by the API.
     */
    public int getStatusCode() {
        return _statusCode;
    }

    /**
     * @return The caption generated by the API.
     */
    public String getCaption() {
        return _caption;
    }

    /**
     * @return The set of improvement tips returned by the API.
     */
    public Set<ImprovementTip> getImprovementTips() {
        return new HashSet<>(_improvementTips);
    }
}