package com.lima2017.neuralguide.api;

import android.support.annotation.NonNull;
import android.support.annotation.Nullable;

import java.net.HttpURLConnection;
import java.util.HashSet;
import java.util.Set;

/**
 * A DTO for passing the results of an image captioning attempt to the user.
 *
 * For Neural Guide WebAPI v0.1
 *
 * @author Henry Thompson
 * @version 1.0
 */

public class ImageCaptionResult {
    /** The status code of the captioning attempt. */
    private final int _statusCode;

    /** The actual caption returned by the server. */
    private final String _caption;

    /** The successful classification parameter returned by the neural net */
    private final boolean _classificationSuccess;

    /** The list of improvements suggested by the server. */
    private final Set<ImprovementTip> _improvementTips;

    /**
     * The result of querying the API to obtain a caption for the image.
     * @param statusCode The status code associated with the result.
     * @param data The data returned about the image.
     */
    public ImageCaptionResult(final int statusCode, @NonNull final NeuralGuideResultData data) {
        _statusCode = statusCode;
        _classificationSuccess = data.getClassificationSuccess();
        if (_classificationSuccess) {
            _caption = data.getText();
        } else {
            _caption = null;
        }
        _improvementTips = null;
    }

    /**
     * The result of a failed API query to obtain a caption for the image.
     * @param statusCode The status code associated with the result.
     */
    public ImageCaptionResult(final int statusCode) {
        _statusCode = statusCode;
        _classificationSuccess = false;
        _caption = null;
        _improvementTips = null;
    }

    /**
     * @return <code>true</code> if and only if the API successfully generated a caption for the
     * image, even if it is not confident about the result.
     */
    public boolean success() {
        return _statusCode == HttpURLConnection.HTTP_OK;
    }

    /**
     * @return The HTTP status code returned by the API.
     */
    public int getStatusCode() {
        return _statusCode;
    }

    /**
     * @return The caption generated by the API.
     */
    @Nullable
    public String getCaption() {
        return _caption;
    }

    /**
     * @return The set of improvement tips returned by the API.
     */
    @NonNull
    public Set<ImprovementTip> getImprovementTips() {
        return new HashSet<>(_improvementTips);
    }
}