package com.lima2017.neuralguide.api;

import android.support.annotation.NonNull;
import android.support.annotation.Nullable;

import com.lima2017.neuralguide.api.web.NeuralGuideResultData;

import java.util.HashSet;
import java.util.Set;

import java8.util.Optional;

/**
 * A DTO for passing the results of an image captioning attempt to the user.
 *
 * For Neural Guide WebAPI v0.1
 *
 * @author Henry Thompson
 * @author Tamara Norman
 * @version 1.0
 */

public class ImageCaptionResult {
    /** The actual caption returned by the server. */
    private final String _caption;

    /** The list of improvements suggested by the server. */
    private final HashSet<ImprovementTip> _improvementTips;

    /**
     * The result of querying the API to obtain a caption for the image.
     * @param caption The caption returned by the API.
     * @param improvementTips Tips from the server for improving the results.
     */
    public ImageCaptionResult(@Nullable final String caption,
                              @NonNull final Set<ImprovementTip> improvementTips) {
        _caption = caption;
        _improvementTips = new HashSet<>(improvementTips);
    }

    /**
     * @return <code>true</code> if and only if the API successfully generated a caption for the
     * image, even if it is not confident about the result.
     */
    public boolean success() {
        return _caption != null;
    }

    /** @return The caption generated by the API. */
    @NonNull
    public Optional<String> getCaption() {
        return Optional.ofNullable(_caption);
    }

    /** @return The set of improvement tips returned by the API. */
    @NonNull
    public HashSet<ImprovementTip> getImprovementTips() {
        return _improvementTips;
    }
}