package com.lima2017.neuralguide.api;

/**
 * Represents the format of the data section of the Json received by the client.
 */
public class NeuralGuideResultData {
    /**The text returned in the Json to show to the user*/
    private String mText;

    /**The improvement tips received to be conveyed to the user*/
    private String[] mImprovementTips;

    /**The confidence interval returned from the server*/
    private int mConfidence;

    /**Whether the neural network returned a successful response*/
    private boolean mClassificationSuccess;

    /**
     * @return The text to be displayed to the client
     */
    public String getText(){
        return mText;
    }

    /**
     * @return The improvement tips generated by the server on how to improve the result
     */
    public String[] getImprovementTips(){
        return mImprovementTips;
    }

    /**
     * @return The confidence interval generated by the neural net
     */
    public int getConfidence(){
        return mConfidence;
    }

    /**
     * @return The classification status of the neural net indicating if text exists
     */
    public boolean getClassificationSuccess () { return mClassificationSuccess; }

}
