package com.lima2017.neuralguide.api;

/**
 * Represents the format of the data section of the Json received by the client.
 */
public class NeuralGuideResultData {
    /**The text returned in the Json to show to the user*/
    private String mText;

    /**The improvement tips received to be conveyed to the user*/
    private String[] mImprovementTips;

    /**The confidence interval returned from the server*/
    private int mConfidence;

    /**
     * @return The text to be displayed to the client
     */
    public String getText(){
        return mText;
    }

    /**
     * @param text Set by the Json libary(need to check if needed)
     */
    public void setText(String text){
        this.mText = text;
    }

    /**
     * @return The improvement tips generated by the server on how to improve the result
     */
    public String[] getImprovementTips(){
        return mImprovementTips;
    }

    /**
     * @param improvementTips Set by the Json libary(need to check if needed)
     */
    public void setImprovementTips(String[] improvementTips){
        this.mImprovementTips = improvementTips;
    }

    /**
     * @return The confidence interval generated by the neural net
     */
    public int getConfidence(){
        return mConfidence;
    }

    /**
     * @param confidence Set by the Json libary(need to check if needed)
     */
    public void setConfidence(int confidence){
        this.mConfidence = confidence;
    }
}
